services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: laravel_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8080:80"

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel
    env_file: ./src/.env
    working_dir: /app
    restart: always
    expose:
      - "9000"